language: python
dist: focal
python: 3.9-dev
before_install:
  - pip install -r requirements-dev.txt
script:
  - make lint
  - ./setup.py install
  - pypicache --once-only --frontend-url https://travis-ci.org/github/AMDmi3/pypicache --dump-path dump.json
