language: python
os: linux
dist: focal
python: 3.9-dev
services:
  - postgresql
before_install:
  - pip install -r requirements-dev.txt
  - sudo -u postgres psql -c "CREATE DATABASE pypicache"
  - sudo -u postgres psql -c "CREATE USER pypicache WITH PASSWORD 'pypicache'"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE pypicache TO pypicache"
script:
  - make lint
  - ./setup.py install
  - pypicache --once-only --frontend-url https://travis-ci.org/github/AMDmi3/pypicache --dump-path dump.json
